name: Docker build and test

on:
  workflow_dispatch 
# you can trigger on anything you want

jobs:
  build:
   runs-on: ubuntu-latest
  
   steps:
     - uses: actions/checkout@v2
     - name: Build Docker image 
       run: docker build -t hello-world .
     - name: Run tests inside the container
       run: docker images 
#     - name: Run console 
#       run: docker run -it hello-world /bin/bash/
     - name: Run container 
       run: docker run hello-world 
     -
       name: Login to Docker Hub
       uses: docker/login-action@v2
       with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
     - name: Tag image
       run: docker tag hello-world:latest tuhao910/python/hello-world:latest
     - name: Run tests inside the container
       run: docker images ls 
     - name: Push image 
       run: docker push tuhao910/python/hello-world:latest
            
